export const ERRO_CADASTRO = 'Erro no cadastro!'
export const EMAIL_EM_USO = 'Este email já está sendo utilizado.'
export const CONTA_CRIADA = 'Conta criada!'
export const REDIRECIONAR_PARA_LOGIN = 'Você será redirecionado para a tela de login.'
export const TENTE_NOVAMENTE = 'Por favor, tente novamente mais tarde.'
export const AUTH_CREDENCIAL_INVALIDA = 'auth/invalid-credential'
export const ERRO_CREDENCIAIS_INVALIDAS = 'Credenciais inválidas!'
export const ERRO_FECHAR_POPUP = 'Autenticação interrompida!'